[package]
name = "oscoin"
version = "0.1.0"
authors = [
  "Alexandre Baldé <alexandre@monadic.xyz>",
  "Thomas Scholtes <thomas@monadic.xyz>"
]
edition = "2018"

[dependencies]
# We require the patch https://github.com/tomusdrw/rust-web3/pull/242.
# Once a new version of web3 is released we can update it.
web3 = { git = "https://github.com/tomusdrw/rust-web3.git", rev = "b2aa7336bc9bf192f7959e79525a6d2667ff4c85" }
env_logger = "0.6.2"
hex = "0.3.1"
clap = "2.31"
oscoin_client = { path = "./client" }

[workspace]
members = ["ledger"]
