[package]
name = "oscoin"
version = "0.1.0"
authors = [
  "Alexandre Baldé <alexandre@monadic.xyz>",
  "Thomas Scholtes <thomas@monadic.xyz>"
]
edition = "2018"

[dependencies]
web3 = "0.8.0"
env_logger = "0.6.2"
hex = "0.3.1"
clap = "2.31"
oscoin_ledger = { path = "./ledger", features = ["std"] }
oscoin_client = { path = "./client" }

[workspace]
