jobs:
  build:
    docker:
      - image: circleci/rust:1.36-buster

    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export RUSTUP_HOME=$HOME/.rustup' >> $BASH_ENV
            echo 'export CARGO_HOME=$HOME/.cargo' >> $BASH_ENV
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - restore_cache:
          keys:
          - rustup-v3-{{ checksum "rust-toolchain" }}
      - run:
          name: Install components
          command: |
            rustup component add rustfmt
            rustup target add wasm32-unknown-unknown
      - save_cache:
          key: rustup-v3-{{ checksum "rust-toolchain" }}
          paths:
            - "~/.rustup"

      - restore_cache:
          keys:
          - cargo-target-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Check formatting
          command: |
            cargo fmt -- --check
      - run:
          name: Build
          command: |
            RUSTFLAGS="-D warnings" cargo build

      - save_cache:
          # "epoch" is here to ensure that we upload a new cache on each build
          key: cargo-target-v1-{{ checksum "Cargo.lock" }}-{{ epoch }}
          paths:
            - "~/.cargo"
            - "./target"
