steps:
  - label: "Install components; check formatting; build; build the ledger, run the linter, start a Parity Ethereum node and run tests."
    commands:
      - 'cargo build --package pwasm-utils-cli --bin wasm-build'
      - 'cargo fmt --all -- --check'
      - 'RUSTFLAGS="-D warnings" cargo build --all'
      - 'RUSTFLAGS="-D warnings" ./tools/build-ledger-wasm'
      - 'cargo clippy --all --all-targets -- -D warnings'
      - './dev-node/run &'
      - 'cargo test --all --color=always -- --test-threads=1'
    env:
      DOCKER_IMAGE: gcr.io/opensourcecoin/oscoin-pwasm-ci-base@sha256:e4d8ecc891144ffe8bb5342bb829d3eef22bb9176bf5ba9cf371a3c8a4271ce2
      DOCKER_FILE: ci/base-image/Dockerfile
    agents:
      platform: "linux"
      production: "true"