#!/bin/bash
#
# Build the ledger code as Wasm and prepare it for parity ethereum.
#
# Creates ./target/oscoin_ledger.wasm.
#

set -euo pipefail

# Rust flags to make the Wasm output small.
rust_flags="${RUSTFLAGS:-""}"
rust_flags+=" -C panic=abort"
rust_flags+=" -C lto=yes"
rust_flags+=" -C opt-level=z"
# Restricting the stack-size limits the initial memory size and memory
# requirements. The code cannot run on chain otherwise and `wasm-build`
# produces invalid Wasm.
rust_flags+=" -C link-args=-zstack-size=65536"

target=wasm32-unknown-unknown
name=oscoin_ledger_pwasm

RUSTFLAGS=$rust_flags\
  cargo build \
  --package $name \
  --release \
  --target $target

./target/debug/wasm-build \
  --target $target \
  --save-raw ./target/${name}_raw.wasm \
  ./target $name

if which wasm2wat >/dev/null 2>&1 ; then
  wasm2wat \
    ./target/$target/release/$name.wasm \
    > ./target/$target/release/$name.wat
  wasm2wat \
    ./target/$name.wasm \
    > ./target/$name.wat
  wasm2wat \
    ./target/${name}_raw.wasm \
    > ./target/${name}_raw.wat
fi
